project_name: sdos

env:
  - GO111MODULE=on

build:
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/kuaifan/sdos/v2/version.Version={{ .Version }} -X github.com/kuaifan/sdos/v2/version.CommitSHA={{ .ShortCommit }}
  main: main.go
  binary: sdos
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386

archives:
  -
    name_template: "{{.Os}}-{{.Arch}}{{if .Arm}}v{{.Arm}}{{end}}-{{ .ProjectName }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    dockerfile: manage.Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
    image_templates:
      - "kuaifan/sdos:manage-{{ .Tag }}-amd64"
  -
    dockerfile: manage.Dockerfile
    use_buildx: true
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goos: linux
    goarch: arm64
    image_templates:
      - "kuaifan/sdos:manage-{{ .Tag }}-arm64"
docker_manifests:
  - name_template: "kuaifan/sdos:manage-{{ .Tag }}"
    image_templates:
      - "kuaifan/sdos:manage-{{ .Tag }}-amd64"
      - "kuaifan/sdos:manage-{{ .Tag }}-arm64"